### ISSUE TITLE
Krew install plugin not working

### ISSUE THREAD

**Issue by josephlim75** [jimmidyson/asdf-krew#3]
Hi, I am using asdf krew to install a plugin called `konfig`.  After i installed, the plugin is not able to use.  I have to manually link it to `/usr/loca/bin/kubectl-kong` in order to use it.  Some help would be appreciated

```
❯ asdf plugin-list
golang
krew
kubectl
python
terraform

❯ asdf list krew
  0.4.2

❯ kubectl krew version
OPTION            VALUE
GitTag            v0.4.2
GitCommit         6fcdb79
IndexURI          https://github.com/kubernetes-sigs/krew-index.git
BasePath          /Users/jlim/.asdf/installs/krew/0.4.2
IndexPath         /Users/jlim/.asdf/installs/krew/0.4.2/index/default
InstallPath       /Users/jlim/.asdf/installs/krew/0.4.2/store
BinPath           /Users/jlim/.asdf/installs/krew/0.4.2/bin
DetectedPlatform  darwin/amd64

❯ kubectl krew list
PLUGIN  VERSION
konfig  v0.2.6
krew    v0.4.2

❯ ls -la /Users/jlim/.asdf/installs/krew/0.4.2/bin
total 0
drwxr-xr-x  4 jlim  staff  128 Jan 15 20:32 .
drwxr-xr-x  6 jlim  staff  192 Jan 15 20:29 ..
lrwxr-xr-x  1 jlim  staff   69 Jan 15 20:32 kubectl-konfig -> /Users/jlim/.asdf/installs/krew/0.4.2/store/konfig/v0.2.6/konfig-krew
lrwxr-xr-x  1 jlim  staff   60 Jan 15 20:29 kubectl-krew -> /Users/jlim/.asdf/installs/krew/0.4.2/store/krew/v0.4.2/krew

❯ kubectl konfig
Error: unknown command "konfig" for "kubectl"

Did you mean this?
        config

Run 'kubectl --help' for usage.

```

**Comment by jimmidyson** [comment]
That looks like `/Users/jlim/.asdf/installs/krew/0.4.2/bin` isn't being put in `PATH` by `asdf` :thinking: Can you share what `PATH` is set to please?

**Comment by josephlim75** [comment]
I noticed that in order for `kubectl` plugin to able to find its extensions, it has to be part of the `PATH`.  Unless the `kubectl-konfig` is located in `~/.asdf/shims`, otherwise it will not find it.  `kubectl-krew` is in the shim folder, therefore, `kubectl krew` works, but not `kubectl konfig`

If we add `/Users/jlim/.asdf/installs/krew/0.4.2/bin`, i believe it will work but I think what needs to happen is to make `kubectl-konfig` get into the shim folder.  Just my 2 cents.  Because if i want to switch version between `krew`,  then the path will no longer work and have to be manually change as well.

```/Users/jlim/.asdf/shims:/usr/local/opt/asdf/libexec/bin:/Users/jlim/.poetry/bin:/Users/jlim/.sdkman/candidates/maven/current/bin:/Users/jlim/.sdkman/candidates/java/current/bin:/Users/jlim/.sdkman/candidates/gradle/current/bin:/Users/jlim/bin:/Users/jlim/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/local/go/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jlim/.cache/zsh4humans/v5/fzf/bin:/opt/kroleg/mc/bin```

**Comment by josephlim75** [comment]
In addition to that, i think there is a problem installing multiple version.  I can't seems to install other version other than `v0.4.2`

**Comment by jimmidyson** [comment]
@josephlim75 You will need to reshim after installing a krew plugin - run `asdf reshim krew`. Just tested and this works fine:

```shell
 $kubectl krew install konfig
Updated the local copy of plugin index.
Installing plugin: konfig
Installed plugin: konfig
\
 | Use this plugin:
 | 	kubectl konfig
 | Documentation:
 | 	https://github.com/corneliusweig/konfig
/
WARNING: You installed plugin "konfig" from the krew-index plugin repository.
   These plugins are not audited for security by the Krew maintainers.
   Run them at your own risk.
root@05775c9f76d3:/#
root@05775c9f76d3:/# kubectl plugin list
The following compatible plugins are available:

/root/.asdf/shims/kubectl-krew
root@05775c9f76d3:/# asdf reshim krew

root@05775c9f76d3:/# kubectl plugin list
The following compatible plugins are available:

/root/.asdf/shims/kubectl-konfig
/root/.asdf/shims/kubectl-krew

root@05775c9f76d3:/# kubectl konfig
kubectl konfig helps to merge, split or import kubeconfig files

USAGE:
  kubectl konfig merge [--preserve-structure,-p] <CONFIG>..
     Merge multiple kubeconfigs into one.
     -p  prevents flattening which will make the result less portable.

  kubectl konfig import [--preserve-structure,-p] [--save,-s] [--stdin,-i] <CONFIG>..
     Import the given configs into your current kubeconfig (respects KUBECONFIG env var).
     -s  writes the result to your ~/.kube/config
     -i  import kubeconfig string from stdin

  kubectl konfig split  <CONTEXT>.. [--kubeconfig,-k <CONFIG>]
  kubectl konfig export <CONTEXT>.. [--kubeconfig,-k <CONFIG>]
     Export/split off a minimal kubeconfig with the given contexts
      -k  may be repeated or contain a comma-delimited list of input configs.
          When omitted, export from the default kubeconfig.

EXAMPLES:
  Merge new-cfg with your current kubeconfig
    $ kubectl konfig import new-cfg
  and save the result to ~/.kube/config
    $ kubectl konfig import --save new-cfg
  CAVEAT: due to how shells work, the following will lose your current ~/.kube/config
    WRONG $ kubectl konfig import new-cfg > ~/.kube/config

  Export ctx1 and ctx2 into combined.yaml
    $ kubectl konfig export -k ~/.kube/config -k k3s.yaml ctx1 ctx2 > combined.yaml

  Merge two configs
    $ kubectl konfig merge ~/.kube/config k3s.yaml > merged-and-flattened
    or
    $ kubectl konfig merge -p ~/.kube/config k3s.yaml > merged-not-flattened
```

**Comment by jimmidyson** [comment]
> In addition to that, i think there is a problem installing multiple version. I can't seems to install other version other than v0.4.2

@josephlim75 Do you mean that when you run `asdf install krew 0.4.1 && asdf local krew 0.4.1` followed by `kubectl krew version` you get:

```
$ kubectl krew version

OPTION            VALUE
GitTag            v0.4.2
GitCommit         6fcdb79
```

If so, that is due to the design of krew. When you install krew, you download the krew binary and run `kubectl install krew` which actually installs the latest version of krew - krew itself is a krew plugin... I'm sure there is a way to work around this, but I'm wondering what the use case is?

**Comment by jimmidyson** [comment]
@josephlim75 I'm going to close this issue now - if you still have issues or questions, please reopen.
